---
version: "3.3"

# sudo docker-compose --env-file env-stage -f docker-compose-stage.yml up -d

volumes:
  db:

networks:
  default:
    external:
      name: ${DOCKERNET}

services:

  ########################################
  # Database
  ########################################
  db:
    image: "mariadb:latest" #https://hub.docker.com/_/mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DBPASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DBUSER}
    volumes:
      - "db:/var/lib/mysql"

  ########################################
  # App
  ########################################
  app:
    image: "4lights/phpcontainer:latest"
    restart: unless-stopped
    volumes:
      - "./:/data"
    ports:
      - "${DOCKERPORT}:80"

  ########################################
  # PHPMyAdmin (Development)
  ########################################
  # phpmyadmin:
  #    image: phpmyadmin/phpmyadmin:latest
  #    ports: 
  #      - "${DOCKERPHPMYADMIN}:80"
  #    environment:
  #      UPLOAD_LIMIT: '200M'
  #      PMA_USER: "${DBUSER}"
  #      PMA_PASSWORD: "${DBPASSWORD}"
  #      PMA_HOST: "${DBHOST}"

  ########################################
  # Mailhog (Development)
  ########################################
  # mailhog:
  #   image: 'mailhog/mailhog:latest'
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"