---
version: "3.3"

# sudo docker-compose --env-file env-stage -f docker-compose-stage.yml up -d

volumes:
  db:

networks:
  default:
    external:
      name: ${DOCKERNET}

services:

  ########################################
  # Database
  ########################################
  mariadb:
    image: "mariadb:latest" # https://hub.docker.com/_/mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeThisPassword}
      MYSQL_PASSWORD: ${DBPASSWORD:-ChangeToAnotherPassword}
      MYSQL_DATABASE: ${DB:-dbname}
      MYSQL_USER: ${DBUSER:-dbuser}
    volumes:
      - "db:/var/lib/mysql"

  ########################################
  # App
  ########################################
  app:
    image: "${DOCKERIMAGE}:${DOCKERVER}" # https://hub.docker.com/r/4lights/phpcontainer
    restart: unless-stopped
    volumes:
      - "./:/data"
    ports:
      - "${DOCKERPORT:-8000}:80"

  ########################################
  # PHPMyAdmin (Development)
  ########################################
  # phpmyadmin:
  #    image: phpmyadmin/phpmyadmin:latest
  #    ports: 
  #      - "${DOCKERPHPMYADMINPORT:-8001}:8001"
  #    environment:
  #      UPLOAD_LIMIT: '200M'
  #      PMA_USER: "${DBUSER:-dbuser}"
  #      PMA_PASSWORD: "${DBPASSWORD:-ChangeToAnotherPassword}"
  #      PMA_HOST: "mariadb"

  ########################################
  # Mailhog (Development)
  ########################################
  # mailhog:
  #   image: 'mailhog/mailhog:latest'
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"