---
version: "3.3"

volumes:
  db:

networks:
  default:
    external:
      name: ${DOCKERNET}

services:

  # Database
  db:
    #https://hub.docker.com/_/mariadb
    image: mariadb:10.7.1
    restart: always
    container_name: "${DBHOST}"
    environment:
      MYSQL_ROOT_PASSWORD: ${SALT}
      MYSQL_PASSWORD: ${DBPASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DBUSER}
    volumes:
      - "db:/var/lib/mysql"

  # Strapi
  strapi:
    container_name: "${DOCKERNAME}-strapi"
    image: strapi/strapi
    restart: always
    environment:
      DATABASE_CLIENT: 'mysql'
      DATABASE_SSL: 'false'
      DATABASE_NAME: ${DB}
      DATABASE_HOST: ${DBHOST}
      DATABASE_PORT: ${DBPORT}
      DATABASE_USERNAME: ${DBUSER}
      DATABASE_PASSWORD: ${DBPASSWORD}
    ports:
      - "1337:1337"

  # App
  app:
    build: .
    container_name: "${DOCKERNAME}"
    #image: "${DOCKERIMAGE}:${DOCKERVER}"
    restart: always
    volumes:
      - "./:/website"
    ports:
      - "${DOCKERPORT}:80"
