---
version: "3.3"

volumes:
  db:

networks:
  default:
    external:
      name: ${DOCKERNET}

services:

  # Database
  db:
    #https://hub.docker.com/_/mariadb
    image: mariadb:10.7.1
    restart: always
    container_name: "${DBHOST}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DBPASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DBUSER}
    volumes:
      - "db:/var/lib/mysql"

  # App
  app:
    build: .
    container_name: "${DOCKERNAME}"
    #image: "${DOCKERIMAGE}:${DOCKERVER}"
    restart: always
    volumes:
      - "./:/website"
    ports:
      - "${DOCKERPORT}:80"
